// Fallback data for when database connection fails
export const fallbackProductsData = [
  {
    "id": "1",
    "_id": "1",
    "image": "/Fex Solar Light 200watts.jpg",
    "name": "Fex Solar Light 200watts",
    "price": "₦35,000",
    "alt": "Fex Solar Light 200watts",
    "category": "Fex Solar",
    "wattage": 200,
    "description": "High-efficiency solar light perfect for residential and commercial use",
    "features": ["Solar powered", "LED technology", "Weather resistant", "Auto on/off"]
  },
  {
    "id": "2",
    "_id": "2",
    "image": "/Fex Solar Light 400watts.jpg",
    "name": "Fex Solar Light 400watts",
    "price": "₦45,000",
    "alt": "Fex Solar Light 400watts",
    "category": "Fex Solar",
    "wattage": 400,
    "description": "Medium power solar lighting solution for larger areas",
    "features": ["Solar powered", "LED technology", "Weather resistant", "Auto on/off"]
  },
  {
    "id": "3",
    "_id": "3",
    "image": "/Fex Solar Light 600watts.jpg",
    "name": "Fex Solar Light 600watts",
    "price": "₦55,000",
    "alt": "Fex Solar Light 600watts",
    "category": "Fex Solar",
    "wattage": 600,
    "description": "High-power solar light for extensive illumination",
    "features": ["Solar powered", "LED technology", "Weather resistant", "Auto on/off"]
  },
  {
    "id": "4",
    "_id": "4",
    "image": "/Fex Solar Light 1200watts.jpg",
    "name": "Fex Solar Light 1200watts",
    "price": "₦68,000",
    "alt": "Fex Solar Light 1200watts",
    "category": "Fex Solar",
    "wattage": 1200,
    "description": "Premium high-wattage solar lighting solution",
    "features": ["Solar powered", "LED technology", "Weather resistant", "Auto on/off"]
  },
  {
    "id": "5",
    "_id": "5",
    "image": "/Fex Solar Light 1500watts.jpg",
    "name": "Fex Solar Light 1500watts",
    "price": "₦85,000",
    "alt": "Fex Solar Light 1500watts",
    "category": "Fex Solar",
    "wattage": 1500,
    "description": "Maximum power solar light for industrial applications",
    "features": ["Solar powered", "LED technology", "Weather resistant", "Auto on/off"]
  },
  {
    "id": "6",
    "_id": "6",
    "image": "/KTJ 100watts.jpg",
    "name": "KTJ Fseries 100watts",
    "price": "₦28,000",
    "alt": "KTJ Fseries 100watts",
    "category": "KTJ",
    "wattage": 100,
    "description": "Compact and efficient KTJ solar light for small spaces",
    "features": ["Solar powered", "LED technology", "Compact design", "Energy efficient"]
  },
  {
    "id": "7",
    "_id": "7",
    "image": "/KTJ 150watts.jpg",
    "name": "KTJ 150watts",
    "price": "₦37,000",
    "alt": "KTJ 150watts",
    "category": "KTJ",
    "wattage": 150,
    "description": "Reliable mid-range KTJ solar lighting solution",
    "features": ["Solar powered", "LED technology", "Durable build", "Easy installation"]
  },
  {
    "id": "8",
    "_id": "8",
    "image": "/KTJ 590 150watts.jpg",
    "name": "KTJ 590 150watts",
    "price": "₦39,000",
    "alt": "KTJ 590 150watts",
    "category": "KTJ",
    "wattage": 150,
    "description": "Advanced KTJ 590 series with enhanced features",
    "features": ["Solar powered", "LED technology", "590 series design", "Weather resistant"]
  },
  {
    "id": "9",
    "_id": "9",
    "image": "/KTJ 300watts.jpg",
    "name": "KTJ 300watts",
    "price": "₦67,000",
    "alt": "KTJ 300watts",
    "category": "KTJ",
    "wattage": 300,
    "description": "High-performance KTJ solar light for commercial use",
    "features": ["Solar powered", "LED technology", "Commercial grade", "Long-lasting"]
  },
  {
    "id": "10",
    "_id": "10",
    "image": "/KTJ 300watts with Panel.jpg",
    "name": "KTJ 300watts with Panel",
    "price": "₦70,000",
    "alt": "KTJ 300watts with Panel",
    "category": "KTJ",
    "wattage": 300,
    "description": "Complete KTJ system with integrated solar panel",
    "features": ["Solar powered", "LED technology", "Integrated panel", "Complete system"]
  },
  {
    "id": "11",
    "_id": "11",
    "image": "/KTJ 350watts.jpg",
    "name": "KTJ 350watts",
    "price": "₦72,000",
    "alt": "KTJ 350watts",
    "category": "KTJ",
    "wattage": 350,
    "description": "Premium KTJ solar lighting with enhanced output",
    "features": ["Solar powered", "LED technology", "High output", "Premium quality"]
  },
  {
    "id": "12",
    "_id": "12",
    "image": "/KTJ 450watts.jpg",
    "name": "KTJ 450watts",
    "price": "₦40,000",
    "alt": "KTJ 450watts",
    "category": "KTJ",
    "wattage": 450,
    "description": "High-capacity KTJ solar light for large areas",
    "features": ["Solar powered", "LED technology", "Large coverage", "Efficient design"]
  },
  {
    "id": "13",
    "_id": "13",
    "image": "/KTJ 500watts.jpg",
    "name": "KTJ 500watts",
    "price": "₦60,000",
    "alt": "KTJ 500watts",
    "category": "KTJ",
    "wattage": 500,
    "description": "Professional-grade KTJ solar lighting solution",
    "features": ["Solar powered", "LED technology", "Professional grade", "High reliability"]
  },
  {
    "id": "14",
    "_id": "14",
    "image": "/KTJ 1300watts.jpg",
    "name": "KTJ 1300watts",
    "price": "₦95,000",
    "alt": "KTJ 1300watts",
    "category": "KTJ",
    "wattage": 1300,
    "description": "Ultra-high power KTJ solar light for industrial use",
    "features": ["Solar powered", "LED technology", "Ultra-high power", "Industrial grade"]
  },
  {
    "id": "15",
    "_id": "15",
    "image": "/KTj Yseries.jpg",
    "name": "KTJ Y-Series",
    "price": "₦52,000",
    "alt": "KTJ Y-Series",
    "category": "KTJ",
    "wattage": 300,
    "description": "Innovative Y-Series design with modern aesthetics",
    "features": ["Solar powered", "LED technology", "Y-series design", "Modern aesthetics"]
  },
  {
    "id": "16",
    "_id": "16",
    "image": "/De Cecon LED Solar Light 600w.jpg",
    "name": "De Cecon LED Solar Light 600w",
    "price": "₦58,000",
    "alt": "De Cecon LED Solar Light 600w",
    "category": "De Cecon",
    "wattage": 600,
    "description": "Premium De Cecon LED solar light with advanced features",
    "features": ["Solar powered", "LED technology", "Premium build", "Advanced features"]
  },
  {
    "id": "17",
    "_id": "17",
    "image": "/De Cecon LED Solar Light 800w.jpg",
    "name": "De Cecon LED Solar Light 800w",
    "price": "₦65,000",
    "alt": "De Cecon LED Solar Light 800w",
    "category": "De Cecon",
    "wattage": 800,
    "description": "High-power De Cecon LED for extensive illumination",
    "features": ["Solar powered", "LED technology", "High power", "Wide coverage"]
  },
  {
    "id": "18",
    "_id": "18",
    "image": "/De Cecon LED Solar Light 1000w.jpg",
    "name": "De Cecon LED Solar Light 1000w",
    "price": "₦78,000",
    "alt": "De Cecon LED Solar Light 1000w",
    "category": "De Cecon",
    "wattage": 1000,
    "description": "Ultra-bright De Cecon LED for large area lighting",
    "features": ["Solar powered", "LED technology", "Ultra-bright", "Large area coverage"]
  },
  {
    "id": "19",
    "_id": "19",
    "image": "/De Cecon LED Solar Light 1200w.jpg",
    "name": "De Cecon LED Solar Light 1200w",
    "price": "₦88,000",
    "alt": "De Cecon LED Solar Light 1200w",
    "category": "De Cecon",
    "wattage": 1200,
    "description": "Maximum output De Cecon LED for commercial applications",
    "features": ["Solar powered", "LED technology", "Maximum output", "Commercial grade"]
  },
  {
    "id": "20",
    "_id": "20",
    "image": "/EcoBoost Indoor.jpg",
    "name": "EcoBoost Indoor Solar Light",
    "price": "₦25,000",
    "alt": "EcoBoost Indoor Solar Light",
    "category": "EcoBoost",
    "wattage": 50,
    "description": "Indoor solar lighting solution for homes and offices",
    "features": ["Solar powered", "LED technology", "Indoor use", "Compact design"]
  },
  {
    "id": "21",
    "_id": "21",
    "image": "/Highway Street Light.jpg",
    "name": "Highway Street Light",
    "price": "₦120,000",
    "alt": "Highway Street Light",
    "category": "Street Lights",
    "wattage": 1000,
    "description": "Professional highway street lighting for main roads",
    "features": ["Solar powered", "LED technology", "Highway grade", "Weather resistant"]
  },
  {
    "id": "22",
    "_id": "22",
    "image": "/Highway Street Light 200watts.jpg",
    "name": "Highway Street Light 200watts",
    "price": "₦115,000",
    "alt": "Highway Street Light 200watts",
    "category": "Street Lights",
    "wattage": 200,
    "description": "Efficient highway street light for secondary roads",
    "features": ["Solar powered", "LED technology", "Highway approved", "Energy efficient"]
  },
  {
    "id": "23",
    "_id": "23",
    "image": "/IP65 with Metallic Casing.jpg",
    "name": "IP65 with Metallic Casing",
    "price": "₦85,000",
    "alt": "IP65 with Metallic Casing",
    "category": "Industrial",
    "wattage": 500,
    "description": "Industrial-grade solar light with IP65 protection",
    "features": ["Solar powered", "LED technology", "IP65 rated", "Metallic casing"]
  },
  {
    "id": "24",
    "_id": "24",
    "image": "/Multiple lens Solar camera street light.jpg",
    "name": "Multiple Lens Solar Camera Street Light",
    "price": "₦150,000",
    "alt": "Multiple Lens Solar Camera Street Light",
    "category": "Smart Lights",
    "wattage": 800,
    "description": "Advanced solar street light with integrated security cameras",
    "features": ["Solar powered", "LED technology", "Security cameras", "Smart features"]
  },
  {
    "id": "25",
    "_id": "25",
    "image": "/Single Lens Camera Solar Street Light.jpg",
    "name": "Single Lens Camera Solar Street Light",
    "price": "₦125,000",
    "alt": "Single Lens Camera Solar Street Light",
    "category": "Smart Lights",
    "wattage": 600,
    "description": "Solar street light with single integrated security camera",
    "features": ["Solar powered", "LED technology", "Security camera", "Motion detection"]
  }
];